### ISSUE TITLE
[FEAT] - Update ESLint rules to ES6 2020

### ISSUE THREAD

**Issue by elit-altum** [elit-altum/AuthExp-Express-Starter#2]
**Is your feature request related to a problem? Please describe.**
Currently ESLint marks ES6 syntax like arrow functions, ```const``` and ```class``` keywords etc. as a linting issue.

**Describe the solution you'd like**
ESLint rules should be fixed so that the new ES6 syntax is not linted as an error.

**Additional context**
Screenshot: 
Arrow functions being linted by ESLint
![image](https://user-images.githubusercontent.com/41413622/93669956-21b8b880-fab5-11ea-82aa-458f52058ec9.png)

**Would you like to work on the issue?**
No, this is a beginner only issue.

**Comment by 16sweetyjain** [comment]
i would like to work on this issue. would you please let me know the prerequisites to start with it?

**Comment by elit-altum** [comment]
Hey @16sweetyjain!
Thank you for your interest in this issue but @raj5036 is already working on this. Please have a look at https://github.com/elit-altum/AuthExp-Express-Starter/issues/6 if you are still interested in contributing. They both are related.

**Comment by elit-altum** [comment]
@raj5036 for all future open source contributions please inform others that you are working on an issue by commenting on that issue first. It avoids duplicate PRs and others doing the same work twice.

Cheers 🥂

**Comment by raj5036** [comment]
OKay I will remember that @elit-altum . Thanks.

**Comment by raj5036** [comment]
Do I need to create a new PR to make it count towards Hacktoberfest?

**Comment by elit-altum** [comment]
Closed via https://github.com/elit-altum/AuthExp-Express-Starter/pull/5
