### ISSUE TITLE
[FEAT] - Setup Prettier as the default formatter instead of ESLint

### ISSUE THREAD

**Issue by elit-altum** [elit-altum/AuthExp-Express-Starter#6]
**Is your feature request related to a problem? Please describe.**
Currently ESLint is being as the default style guide but moving to prettier would be more consistent as it also supports Angular, Vue and other framework syntax.

**Describe the solution you'd like**
Setup prettier as the default formatter and a ```.prettierrc``` file for rule modifications.

**Additional context**
Editors like VSCode provide out of the box support for prettier but having a fallback would be a safer option.

**Would you like to work on the issue?**
No, This is a beginner only issue.

**Comment by elit-altum** [comment]
For getting started you can read more [here](https://sourcelevel.io/blog/how-to-setup-eslint-and-prettier-on-node)

**Comment by 16sweetyjain** [comment]
I want to work on this issue.

**Comment by 16sweetyjain** [comment]
git push origin swejain/prettier
remote: Permission to elit-altum/AuthExp-Express-Starter.git denied to 16sweetyjain.
fatal: unable to access 'https://github.com/elit-altum/AuthExp-Express-Starter.git/': The requested URL returned error: 403

I am getting this error while pushing my code. May you please help?

**Comment by 16sweetyjain** [comment]
https://github.com/desktop/desktop/issues/3889
I referred to this but it didnt help.

**Comment by elit-altum** [comment]
@16sweetyjain If you go to your local fork and view the branch ```swejain/prettier``` there is an option to create a PR. Please create a PR first I believe ve you were directly pushing to the main repo.
Hope this helps!

**Comment by 16sweetyjain** [comment]
i was pushing to branch swejain/prettier

**Comment by elit-altum** [comment]
@16sweetyjain  Okay no problems maybe this something we can look into further. Can you create a PR?

**Comment by 16sweetyjain** [comment]
yes

**Comment by elit-altum** [comment]
Closed via https://github.com/elit-altum/AuthExp-Express-Starter/pull/10
